service: defender-as-code-template
configValidationMode: error
frameworkVersion: '3'

provider:
  name: defender
  stage: ${opt:stage, 'dev'}
  stackName: 'mystack'
  # SSOT: use this template as a single source of truth.
  # This will delete Defender resources (with the exception of Relayers) not found in this template upon deployment.
  ssot: false

defender:
  key: '${env:TEAM_API_KEY}'
  secret: '${env:TEAM_API_SECRET}'

resources:
  actions:
    action-example-1:
      name: 'Hello world from serverless'
      path: './actions/hello-world'
      relayer: ${self:resources.relayers.relayer-1}
      trigger:
        type: 'schedule'
        frequency: 1500
      paused: false
      # optional - unencrypted and scoped to the individual action
      environment-variables:
        hello: 'world!'

  policies:
    policy-1:
      gas-price-cap: 1000
      whitelist-receivers:
        - '0x0f06aB75c7DD497981b75CD82F6566e3a5CAd8f2'
      eip1559-pricing: true
      private-transactions: true

  relayers:
    relayer-1:
      name: 'My Relayer'
      network: 'goerli'
      min-balance: 1000
      policy: ${self:resources.policies.policy-1}
      api-keys:
        - key1

  contracts:
    contract-1:
      name: 'Demo-Flash'
      address: '0xA91382E82fB676d4c935E601305E5253b3829dCD'
      network: 'mainnet'
      # optional
      abi: ${file(./abis/demoflash.json.abi)}
      # optional
      nat-spec: null

plugins:
  - '@openzeppelin/defender-as-code'
